version: "3"

services:
    api:
        image: fibonacci-api:latest
        build: ./api
        ports:
            - "1234:1234"
        environment:
            - REDIS_URL=redis://redis:6379
    redis:
        image: redis
        ports:
            - "6379:6379"
    web:
        image: fibonacci-web:latest
        build: ./web
        ports:
            - "8080:8080"
        environment:
            - API_URL=http://api:1234/api
